<?php

namespace Database\Seeders;

use App\Models\Category;
use App\Models\Equipment;
use Illuminate\Database\Seeder;

class EquipmentSeeder extends Seeder
{
    public function run(): void
    {
        // Truncate first to avoid duplicates on re-run
        Equipment::query()->delete();

        // Získání ID kategorií
        $categories = Category::pluck('id', 'slug')->toArray();

        $equipment = [
            // Audio - Mikrofony
            [
                'name' => 'Shure SM58',
                'description' => 'Dynamický vokální mikrofon, průmyslový standard pro živé koncerty',
                'category' => 'audio',
                'category_id' => $categories['audio'] ?? null,
                'category_id' => $categories['audio'] ?? null,
                'model' => 'SM58-LC',
                'serial_number' => 'SM58-001',
                'rfid_tag' => 'RFID-SM58-001',
                'quantity_available' => 8,
                'is_critical' => true,
                'location' => 'Sklad - Police A1',
                'status' => 'available',
                'purchase_date' => '2023-01-15',
                'purchase_price' => 2890.00,
                'warranty_expiry' => '2025-01-15',
                'maintenance_notes' => 'Kontrola membrány každých 6 měsíců',
                'last_maintenance' => '2025-06-01',
                'next_maintenance' => '2025-12-01',
            ],
            [
                'name' => 'Shure SM57',
                'description' => 'Instrumentální dynamický mikrofon, ideální pro snímání kytar a bicích',
                'category' => 'audio',
                'category_id' => $categories['audio'] ?? null,
                'category_id' => $categories['audio'] ?? null,
                'model' => 'SM57-LC',
                'serial_number' => 'SM57-001',
                'rfid_tag' => 'RFID-SM57-001',
                'quantity_available' => 6,
                'is_critical' => true,
                'location' => 'Sklad - Police A1',
                'status' => 'available',
                'purchase_date' => '2023-01-15',
                'purchase_price' => 2690.00,
                'warranty_expiry' => '2025-01-15',
                'maintenance_notes' => 'Standardní údržba každých 6 měsíců',
                'last_maintenance' => '2025-06-01',
                'next_maintenance' => '2025-12-01',
            ],
            [
                'name' => 'AKG C214',
                'description' => 'Kondenzátorový studiový mikrofon s velkou membránou',
                'category' => 'audio',
                'category_id' => $categories['audio'] ?? null,
                'model' => 'C214',
                'serial_number' => 'AKG-001',
                'rfid_tag' => 'RFID-AKG-001',
                'quantity_available' => 2,
                'is_critical' => false,
                'location' => 'Studio - Skříň B',
                'status' => 'available',
                'purchase_date' => '2024-03-10',
                'purchase_price' => 9990.00,
                'warranty_expiry' => '2026-03-10',
                'maintenance_notes' => 'Citlivé - vyžaduje šetrné zacházení',
                'last_maintenance' => '2025-09-01',
                'next_maintenance' => '2026-03-01',
            ],
            // Audio - Reproboxy
            [
                'name' => 'JBL EON615',
                'description' => 'Aktivní PA reprobox 1000W, 15" bass',
                'category' => 'audio',
                'category_id' => $categories['audio'] ?? null,
                'model' => 'EON615',
                'serial_number' => 'JBL-EON-001',
                'rfid_tag' => 'RFID-JBL-001',
                'quantity_available' => 4,
                'is_critical' => true,
                'location' => 'Hlavní sál',
                'status' => 'available',
                'purchase_date' => '2023-06-20',
                'purchase_price' => 14990.00,
                'warranty_expiry' => '2025-06-20',
                'maintenance_notes' => 'Pravidelná kontrola konektorů a reproduktorů',
                'last_maintenance' => '2025-08-01',
                'next_maintenance' => '2026-02-01',
            ],
            [
                'name' => 'Yamaha DXR12',
                'description' => 'Aktivní 12" stage monitor, 1100W',
                'category' => 'audio',
                'category_id' => $categories['audio'] ?? null,
                'model' => 'DXR12',
                'serial_number' => 'YAM-DXR-001',
                'rfid_tag' => 'RFID-YAM-001',
                'quantity_available' => 2,
                'is_critical' => false,
                'location' => 'Zkušebna 2',
                'status' => 'available',
                'purchase_date' => '2024-02-15',
                'purchase_price' => 16990.00,
                'warranty_expiry' => '2026-02-15',
                'maintenance_notes' => 'Kontrola DSP procesoru',
                'last_maintenance' => '2025-10-01',
                'next_maintenance' => '2026-04-01',
            ],
            // Nástroje - Kytary
            [
                'name' => 'Fender Stratocaster',
                'description' => 'Elektrická kytara American Professional II',
                'category' => 'instrument',
                'category_id' => $categories['instrument'] ?? null,
                'model' => 'Stratocaster AM PRO II',
                'serial_number' => 'FEND-STRAT-001',
                'rfid_tag' => 'RFID-FEND-001',
                'quantity_available' => 1,
                'is_critical' => false,
                'location' => 'Studio Premium',
                'status' => 'available',
                'purchase_date' => '2024-05-10',
                'purchase_price' => 45990.00,
                'warranty_expiry' => '2026-05-10',
                'maintenance_notes' => 'Výměna strun měsíčně, kontrola ladění',
                'last_maintenance' => '2025-11-01',
                'next_maintenance' => '2025-12-01',
            ],
            [
                'name' => 'Gibson Les Paul',
                'description' => 'Elektrická kytara Standard 50s',
                'category' => 'instrument',
                'category_id' => $categories['instrument'] ?? null,
                'model' => 'Les Paul Standard',
                'serial_number' => 'GIBS-LP-001',
                'rfid_tag' => 'RFID-GIBS-001',
                'quantity_available' => 1,
                'is_critical' => false,
                'location' => 'Studio Premium',
                'status' => 'available',
                'purchase_date' => '2023-09-05',
                'purchase_price' => 59990.00,
                'warranty_expiry' => '2025-09-05',
                'maintenance_notes' => 'Kontrola elektroniky a snímačů',
                'last_maintenance' => '2025-10-15',
                'next_maintenance' => '2026-04-15',
            ],
            // Nástroje - Bicí
            [
                'name' => 'Pearl Export',
                'description' => 'Kompletní bicí souprava 5-dílná',
                'category' => 'instrument',
                'category_id' => $categories['instrument'] ?? null,
                'model' => 'Export EXX725S',
                'serial_number' => 'PEARL-EXP-001',
                'rfid_tag' => 'RFID-PEARL-001',
                'quantity_available' => 1,
                'is_critical' => true,
                'location' => 'Hlavní zkušebna',
                'status' => 'in_use',
                'purchase_date' => '2022-11-20',
                'purchase_price' => 24990.00,
                'warranty_expiry' => '2024-11-20',
                'maintenance_notes' => 'Výměna blán dle potřeby, kontrola mechaniky',
                'last_maintenance' => '2025-09-01',
                'next_maintenance' => '2025-12-01',
            ],
            [
                'name' => 'Zildjian A Custom',
                'description' => 'Sada činel pro bicí (Hi-Hat 14", Crash 16", Ride 20")',
                'category' => 'instrument',
                'category_id' => $categories['instrument'] ?? null,
                'model' => 'A Custom Set',
                'serial_number' => 'ZILD-AC-001',
                'rfid_tag' => 'RFID-ZILD-001',
                'quantity_available' => 1,
                'is_critical' => true,
                'location' => 'Hlavní zkušebna',
                'status' => 'in_use',
                'purchase_date' => '2023-03-15',
                'purchase_price' => 18990.00,
                'warranty_expiry' => '2025-03-15',
                'maintenance_notes' => 'Pravidelné čištění, kontrola trhlin',
                'last_maintenance' => '2025-10-01',
                'next_maintenance' => '2026-04-01',
            ],
            // Osvětlení
            [
                'name' => 'Chauvet DJ Intimidator',
                'description' => 'LED Moving Head světlo s efekty',
                'category' => 'lighting',
                'category_id' => $categories['lighting'] ?? null,
                'model' => 'Intimidator Spot 355',
                'serial_number' => 'CHAU-INT-001',
                'rfid_tag' => 'RFID-CHAU-001',
                'quantity_available' => 4,
                'is_critical' => false,
                'location' => 'Technická místnost',
                'status' => 'available',
                'purchase_date' => '2024-01-10',
                'purchase_price' => 12990.00,
                'warranty_expiry' => '2026-01-10',
                'maintenance_notes' => 'Čištění optiky, kontrola motorů',
                'last_maintenance' => '2025-08-01',
                'next_maintenance' => '2026-02-01',
            ],
            [
                'name' => 'ADJ LED Par',
                'description' => 'RGB LED reflektor 64',
                'category' => 'lighting',
                'category_id' => $categories['lighting'] ?? null,
                'model' => '64B LED Pro',
                'serial_number' => 'ADJ-PAR-001',
                'rfid_tag' => 'RFID-ADJ-001',
                'quantity_available' => 8,
                'is_critical' => false,
                'location' => 'Technická místnost',
                'status' => 'available',
                'purchase_date' => '2023-07-15',
                'purchase_price' => 3990.00,
                'warranty_expiry' => '2025-07-15',
                'maintenance_notes' => 'Kontrola LED diod, čištění',
                'last_maintenance' => '2025-07-01',
                'next_maintenance' => '2026-01-01',
            ],
            // Mixážní pulty
            [
                'name' => 'Behringer X32',
                'description' => 'Digitální mixážní pult 32 kanálů',
                'category' => 'mixer',
                'category_id' => $categories['mixer'] ?? null,
                'model' => 'X32 Producer',
                'serial_number' => 'BEH-X32-001',
                'rfid_tag' => 'RFID-BEH-001',
                'quantity_available' => 1,
                'is_critical' => true,
                'location' => 'Hlavní sál - Mix pozice',
                'status' => 'available',
                'purchase_date' => '2023-05-20',
                'purchase_price' => 45990.00,
                'warranty_expiry' => '2025-05-20',
                'maintenance_notes' => 'Aktualizace firmware, záloha nastavení',
                'last_maintenance' => '2025-09-01',
                'next_maintenance' => '2026-03-01',
            ],
            [
                'name' => 'Allen & Heath ZED-14',
                'description' => 'Analogový mixážní pult 14 kanálů',
                'category' => 'mixer',
                'category_id' => $categories['mixer'] ?? null,
                'model' => 'ZED-14',
                'serial_number' => 'AH-ZED-001',
                'rfid_tag' => 'RFID-AH-001',
                'quantity_available' => 2,
                'is_critical' => false,
                'location' => 'Zkušebna 1, Zkušebna 2',
                'status' => 'available',
                'purchase_date' => '2022-08-10',
                'purchase_price' => 12990.00,
                'warranty_expiry' => '2024-08-10',
                'maintenance_notes' => 'Čištění faderů, kontrola konektorů',
                'last_maintenance' => '2025-06-01',
                'next_maintenance' => '2025-12-01',
            ],
            // Nahrávací technika
            [
                'name' => 'Focusrite Scarlett 18i20',
                'description' => 'USB audio interface 18 vstupů / 20 výstupů',
                'category' => 'recording',
                'category_id' => $categories['recording'] ?? null,
                'model' => '18i20 3rd Gen',
                'serial_number' => 'FOC-18I20-001',
                'rfid_tag' => 'RFID-FOC-001',
                'quantity_available' => 1,
                'is_critical' => true,
                'location' => 'Studio Premium',
                'status' => 'available',
                'purchase_date' => '2024-02-01',
                'purchase_price' => 14990.00,
                'warranty_expiry' => '2026-02-01',
                'maintenance_notes' => 'Aktualizace ovladačů',
                'last_maintenance' => '2025-10-01',
                'next_maintenance' => '2026-04-01',
            ],
            [
                'name' => 'Tascam DR-40X',
                'description' => 'Přenosný rekordér 4 stopy',
                'category' => 'recording',
                'category_id' => $categories['recording'] ?? null,
                'model' => 'DR-40X',
                'serial_number' => 'TASC-DR40-001',
                'rfid_tag' => 'RFID-TASC-001',
                'quantity_available' => 2,
                'is_critical' => false,
                'location' => 'Výdejna',
                'status' => 'available',
                'purchase_date' => '2023-11-15',
                'purchase_price' => 5990.00,
                'warranty_expiry' => '2025-11-15',
                'maintenance_notes' => 'Kontrola baterií, čištění',
                'last_maintenance' => '2025-09-01',
                'next_maintenance' => '2026-03-01',
            ],
            // Příslušenství
            [
                'name' => 'XLR kabel 5m',
                'description' => 'Symetrický mikrofonní kabel',
                'category' => 'accessory',
                'category_id' => $categories['accessory'] ?? null,
                'model' => 'PRO XLR-5M',
                'serial_number' => null,
                'rfid_tag' => null,
                'quantity_available' => 20,
                'is_critical' => true,
                'location' => 'Sklad - Kabelový regál',
                'status' => 'available',
                'purchase_date' => '2023-01-10',
                'purchase_price' => 290.00,
                'warranty_expiry' => '2025-01-10',
                'maintenance_notes' => 'Kontrola konektorů, testování průchodnosti',
                'last_maintenance' => '2025-08-01',
                'next_maintenance' => '2026-02-01',
            ],
            [
                'name' => 'Jack kabel 3m',
                'description' => 'Nástrojový kabel 6,3mm jack',
                'category' => 'accessory',
                'category_id' => $categories['accessory'] ?? null,
                'model' => 'PRO JACK-3M',
                'serial_number' => null,
                'rfid_tag' => null,
                'quantity_available' => 15,
                'is_critical' => true,
                'location' => 'Sklad - Kabelový regál',
                'status' => 'available',
                'purchase_date' => '2023-01-10',
                'purchase_price' => 190.00,
                'warranty_expiry' => '2025-01-10',
                'maintenance_notes' => 'Kontrola konektorů',
                'last_maintenance' => '2025-08-01',
                'next_maintenance' => '2026-02-01',
            ],
            [
                'name' => 'Mikrofonní stojan',
                'description' => 'Teleskopický stojan s ramenem',
                'category' => 'accessory',
                'category_id' => $categories['accessory'] ?? null,
                'model' => 'K&M 210/2',
                'serial_number' => null,
                'rfid_tag' => null,
                'quantity_available' => 12,
                'is_critical' => true,
                'location' => 'Sklad - Stojany',
                'status' => 'available',
                'purchase_date' => '2022-12-01',
                'purchase_price' => 990.00,
                'warranty_expiry' => '2024-12-01',
                'maintenance_notes' => 'Kontrola šroubů a kloubů',
                'last_maintenance' => '2025-07-01',
                'next_maintenance' => '2026-01-01',
            ],
            [
                'name' => 'Kytarový stojan',
                'description' => 'Univerzální stojan pro elektrické/akustické kytary',
                'category' => 'accessory',
                'category_id' => $categories['accessory'] ?? null,
                'model' => 'Hercules GS414B',
                'serial_number' => null,
                'rfid_tag' => null,
                'quantity_available' => 6,
                'is_critical' => false,
                'location' => 'Zkušebny - různé',
                'status' => 'available',
                'purchase_date' => '2023-04-15',
                'purchase_price' => 690.00,
                'warranty_expiry' => '2025-04-15',
                'maintenance_notes' => 'Kontrola stability',
                'last_maintenance' => '2025-09-01',
                'next_maintenance' => '2026-03-01',
            ],
            // Nábytek
            [
                'name' => 'Studiová židle',
                'description' => 'Nastavitelná židle pro mix pozici',
                'category' => 'furniture',
                'category_id' => $categories['furniture'] ?? null,
                'model' => 'Studio Pro Chair',
                'serial_number' => null,
                'rfid_tag' => null,
                'quantity_available' => 4,
                'is_critical' => false,
                'location' => 'Studia a zkušebny',
                'status' => 'available',
                'purchase_date' => '2023-06-01',
                'purchase_price' => 2990.00,
                'warranty_expiry' => '2025-06-01',
                'maintenance_notes' => 'Kontrola hydrauliky a koleček',
                'last_maintenance' => '2025-09-01',
                'next_maintenance' => '2026-03-01',
            ],
            [
                'name' => 'Rack skříň 12U',
                'description' => '19" rackový systém pro zařízení',
                'category' => 'furniture',
                'category_id' => $categories['furniture'] ?? null,
                'model' => 'SKB 12U',
                'serial_number' => 'SKB-12U-001',
                'rfid_tag' => 'RFID-SKB-001',
                'quantity_available' => 2,
                'is_critical' => false,
                'location' => 'Technická místnost',
                'status' => 'available',
                'purchase_date' => '2022-10-15',
                'purchase_price' => 8990.00,
                'warranty_expiry' => '2024-10-15',
                'maintenance_notes' => 'Kontrola kolečkek a uzávěrů',
                'last_maintenance' => '2025-05-01',
                'next_maintenance' => '2025-11-01',
            ],
            // Ostatní
            [
                'name' => 'Direct Box (DI)',
                'description' => 'Pasivní DI box pro připojení nástrojů',
                'category' => 'other',
                'category_id' => $categories['other'] ?? null,
                'model' => 'Radial Pro DI',
                'serial_number' => 'RAD-DI-001',
                'rfid_tag' => 'RFID-RAD-001',
                'quantity_available' => 4,
                'is_critical' => false,
                'location' => 'Sklad - Police C2',
                'status' => 'available',
                'purchase_date' => '2023-08-20',
                'purchase_price' => 2490.00,
                'warranty_expiry' => '2025-08-20',
                'maintenance_notes' => 'Kontrola konektorů',
                'last_maintenance' => '2025-08-01',
                'next_maintenance' => '2026-02-01',
            ],
            [
                'name' => 'Power kondicionér',
                'description' => 'Napájecí jednotka s ochranou proti přepětí',
                'category' => 'other',
                'category_id' => $categories['other'] ?? null,
                'model' => 'Furman M-8x2',
                'serial_number' => 'FURM-M8-001',
                'rfid_tag' => 'RFID-FURM-001',
                'quantity_available' => 3,
                'is_critical' => true,
                'location' => 'Technická místnost',
                'status' => 'available',
                'purchase_date' => '2023-02-10',
                'purchase_price' => 4990.00,
                'warranty_expiry' => '2025-02-10',
                'maintenance_notes' => 'Testování ochrany',
                'last_maintenance' => '2025-10-01',
                'next_maintenance' => '2026-04-01',
            ],
        ];

        foreach ($equipment as $item) {
            Equipment::create($item);
        }
    }
}
